-- Koreksi pusat Jalan Wira / Mallengkeri Tamalate Makassar (zona 3 km)

CREATE OR REPLACE FUNCTION public.jalan_wira_lat()
RETURNS DOUBLE PRECISION LANGUAGE SQL IMMUTABLE AS $$ SELECT -5.187700::DOUBLE PRECISION; $$;

CREATE OR REPLACE FUNCTION public.jalan_wira_lng()
RETURNS DOUBLE PRECISION LANGUAGE SQL IMMUTABLE AS $$ SELECT 119.434300::DOUBLE PRECISION; $$;
